version: "3.7"
services:
  bktpostgres:
    image: postgres:11.0
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - bktdata:/var/lib/postgresql/data
  
  bktserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - bktpostgres
    networks:
      - default
    ports:
      - "8080:8080"

volumes:
  bktdata:
